<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (NO_TRANSMITTER?,LAST_LONGITUDE?,LAST_LATITUDE?,REPORTDATE?,NAMA_KAPAL_VMS?,PEMILIK_KAPAL?,NAMA_PERUSAHAAN?,ID_WPP?)+>
  <!ELEMENT NO_TRANSMITTER (#PCDATA)>
  <!ELEMENT LAST_LONGITUDE (#PCDATA)>
  <!ELEMENT LAST_LATITUDE (#PCDATA)>
  <!ELEMENT REPORTDATE (#PCDATA)>
  <!ELEMENT NAMA_KAPAL_VMS (#PCDATA)>
  <!ELEMENT PEMILIK_KAPAL (#PCDATA)>
  <!ELEMENT NAMA_PERUSAHAAN (#PCDATA)>
  <!ELEMENT ID_WPP (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <NO_TRANSMITTER>4520467</NO_TRANSMITTER>
    <LAST_LONGITUDE>116,7531</LAST_LONGITUDE>
    <LAST_LATITUDE>-3,8067</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 03:03:00</REPORTDATE>
    <NAMA_KAPAL_VMS>IBADA - 1</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TRISMAYA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TRISMAYA</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4520463</NO_TRANSMITTER>
    <LAST_LONGITUDE>116,7986</LAST_LONGITUDE>
    <LAST_LATITUDE>-3,9489</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:18:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEMANGET</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>H. SODIKIN BIN SALMAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>H. SODIKIN BIN SALMAN</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957177</NO_TRANSMITTER>
    <LAST_LONGITUDE>95,7981</LAST_LONGITUDE>
    <LAST_LATITUDE>-34,8275</LAST_LATITUDE>
    <REPORTDATE>2015/04/01 23:06:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 102</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>573, 2</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4548845</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,3806</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,4783</LAST_LATITUDE>
    <REPORTDATE>2014/12/03 11:25:00</REPORTDATE>
    <NAMA_KAPAL_VMS>KUMANA 2</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ARAFURA MINA MULYA MARITIM, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ARAFURA MINA MULYA MARITIM, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957182</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,1561</LAST_LONGITUDE>
    <LAST_LATITUDE>-9,4942</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:31:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 103</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957401</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,1631</LAST_LONGITUDE>
    <LAST_LATITUDE>-9,3697</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:30:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 237</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957407</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2061</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7381</LAST_LATITUDE>
    <REPORTDATE>2015/04/12 22:01:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 112</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957412</NO_TRANSMITTER>
    <LAST_LONGITUDE>136,6411</LAST_LONGITUDE>
    <LAST_LATITUDE>-9,06</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 08</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4954495</NO_TRANSMITTER>
    <LAST_LONGITUDE>106,8036</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,1022</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 05:04:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEMBILAN TIMUR JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ADIL KAMARUDDIN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ADIL KAMARUDDIN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4522614</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2075</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7419</LAST_LATITUDE>
    <REPORTDATE>2015/01/06 09:37:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN 2018</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4522616</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,0669</LAST_LONGITUDE>
    <LAST_LATITUDE>-9,5158</LAST_LATITUDE>
    <REPORTDATE>2015/06/01 17:04:00</REPORTDATE>
    <NAMA_KAPAL_VMS>CHARLIE JAYA - 9</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MINA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MINA</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870396</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7947</LAST_LONGITUDE>
    <LAST_LATITUDE>1,7211</LAST_LATITUDE>
    <REPORTDATE>2014/02/28 03:34:00</REPORTDATE>
    <NAMA_KAPAL_VMS>CHRISTINA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>DEWI SRI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>DEWI SRI</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>2936</NO_TRANSMITTER>
    <LAST_LONGITUDE>125,209</LAST_LONGITUDE>
    <LAST_LATITUDE>1,449</LAST_LATITUDE>
    <REPORTDATE>2013/06/24 05:43:48</REPORTDATE>
    <NAMA_KAPAL_VMS>BITUNG RAYA - 1</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BITUNG RAYA ASRI SELARAS, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BITUNG RAYA ASRI SELARAS, PT</NAMA_PERUSAHAAN>
    <ID_WPP>715, 716</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>3049</NO_TRANSMITTER>
    <LAST_LONGITUDE>109,064</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,679</LAST_LATITUDE>
    <REPORTDATE>2013/06/24 05:43:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SURJA REDJEKI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RATNAWATI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RATNAWATI</NAMA_PERUSAHAAN>
    <ID_WPP>712, 713</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870400</NO_TRANSMITTER>
    <LAST_LONGITUDE>99,6039</LAST_LONGITUDE>
    <LAST_LATITUDE>-1,4511</LAST_LATITUDE>
    <REPORTDATE>2014/08/29 21:31:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SIBOLGA NAULI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MARTINUS BUDIMAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MARTINUS BUDIMAN</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870399</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7564</LAST_LONGITUDE>
    <LAST_LATITUDE>0,9994</LAST_LATITUDE>
    <REPORTDATE>2014/02/28 15:08:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SERASI BERSAMA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RUSWANDI SIMATUPANG, SH</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RUSWANDI SIMATUPANG, SH</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870382</NO_TRANSMITTER>
    <LAST_LONGITUDE>106,9211</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,2394</LAST_LATITUDE>
    <REPORTDATE>2014/01/15 15:09:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEMANGAT LAUT JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RONALD SUSILO, ST</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RONALD SUSILO, ST</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4816217</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2075</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7422</LAST_LATITUDE>
    <REPORTDATE>2015/03/27 05:01:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 2010</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4816211</NO_TRANSMITTER>
    <LAST_LONGITUDE>57,4969</LAST_LONGITUDE>
    <LAST_LATITUDE>-20,1561</LAST_LATITUDE>
    <REPORTDATE>2013/10/02 03:01:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR TUNA - 33</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>I GUSTI NGURAH KETUT EKA PUTRA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>I GUSTI NGURAH KETUT EKA PUTRA</NAMA_PERUSAHAAN>
    <ID_WPP>2</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870373</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,5422</LAST_LONGITUDE>
    <LAST_LATITUDE>1,3331</LAST_LATITUDE>
    <REPORTDATE>2013/03/12 06:28:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LESTARI VIII</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJAI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJAI</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4815619</NO_TRANSMITTER>
    <LAST_LONGITUDE>109,6881</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,8667</LAST_LATITUDE>
    <REPORTDATE>2014/03/20 05:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG MAS BERLIAN</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SAMSUL</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SAMSUL</NAMA_PERUSAHAAN>
    <ID_WPP>713, 712</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4815400</NO_TRANSMITTER>
    <LAST_LONGITUDE>109,6925</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,8622</LAST_LATITUDE>
    <REPORTDATE>2014/09/08 07:52:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG MAS FAVORIT</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>IMRAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>IMRAN</NAMA_PERUSAHAAN>
    <ID_WPP>712, 713</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>3091</NO_TRANSMITTER>
    <LAST_LONGITUDE>112,672</LAST_LONGITUDE>
    <LAST_LATITUDE>-5,73</LAST_LATITUDE>
    <REPORTDATE>2013/06/24 03:07:22</REPORTDATE>
    <NAMA_KAPAL_VMS>YUIEE JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>IRAWAN SUGIYONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>IRAWAN SUGIYONO</NAMA_PERUSAHAAN>
    <ID_WPP> </ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4933527</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2236</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7531</LAST_LATITUDE>
    <REPORTDATE>2015/05/12 04:23:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 271</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4933524</NO_TRANSMITTER>
    <LAST_LONGITUDE>111,3122</LAST_LONGITUDE>
    <LAST_LATITUDE>-12,5969</LAST_LATITUDE>
    <REPORTDATE>2015/05/17 12:44:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 31</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>573, 2</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4949262</NO_TRANSMITTER>
    <LAST_LONGITUDE>134,4181</LAST_LONGITUDE>
    <LAST_LATITUDE>-3,92</LAST_LATITUDE>
    <REPORTDATE>2014/12/31 20:54:00</REPORTDATE>
    <NAMA_KAPAL_VMS>AVONA LESTARI 3</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ARULESTARI SAMUDERA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ARULESTARI SAMUDERA, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4905065</NO_TRANSMITTER>
    <LAST_LONGITUDE>93,9161</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,7006</LAST_LATITUDE>
    <REPORTDATE>2014/04/30 05:06:00</REPORTDATE>
    <NAMA_KAPAL_VMS>YORDAN</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ANTHONY ANDRIANA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ANTHONY ANDRIANA</NAMA_PERUSAHAAN>
    <ID_WPP>572, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4905066</NO_TRANSMITTER>
    <LAST_LONGITUDE>111,1106</LAST_LONGITUDE>
    <LAST_LATITUDE>-3,5717</LAST_LATITUDE>
    <REPORTDATE>2014/08/22 16:10:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MAKMUR JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SARTONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SARTONO</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811703521</NO_TRANSMITTER>
    <LAST_LONGITUDE>109,136</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,853</LAST_LATITUDE>
    <REPORTDATE>2015/03/17 04:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>CITRA SAMUDERA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KATIDJAN ANDRIANA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KATIDJAN ANDRIANA</NAMA_PERUSAHAAN>
    <ID_WPP>712, 713</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4933513</NO_TRANSMITTER>
    <LAST_LONGITUDE>121,4581</LAST_LONGITUDE>
    <LAST_LATITUDE>-12,3533</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:13:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEGA PRIMA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AGUS SALIM HINDRATO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AGUS SALIM HINDRATO</NAMA_PERUSAHAAN>
    <ID_WPP>572, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4933520</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2061</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7378</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:24:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 276</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4933505</NO_TRANSMITTER>
    <LAST_LONGITUDE>103,7256</LAST_LONGITUDE>
    <LAST_LATITUDE>1,3097</LAST_LATITUDE>
    <REPORTDATE>2014/12/06 01:46:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MAJU JAYA - 9</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BUN LIE als FENDY</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BUN LIE als FENDY</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4960971</NO_TRANSMITTER>
    <LAST_LONGITUDE>106,8022</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,1011</LAST_LATITUDE>
    <REPORTDATE>2015/06/01 17:57:00</REPORTDATE>
    <NAMA_KAPAL_VMS>RAJAWALI - I</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HERYANTO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HERYANTO</NAMA_PERUSAHAAN>
    <ID_WPP>572, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4960947</NO_TRANSMITTER>
    <LAST_LONGITUDE>86,7633</LAST_LONGITUDE>
    <LAST_LATITUDE>-34,4158</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 04:54:00</REPORTDATE>
    <NAMA_KAPAL_VMS>NAILI - XVIII</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>WENY YUHADI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>WENY YUHADI</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4958152</NO_TRANSMITTER>
    <LAST_LONGITUDE>119,0467</LAST_LONGITUDE>
    <LAST_LATITUDE>-10,0814</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 05:06:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SANJAYA - 66</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HENRY LAU</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HENRY LAU</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4958954</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2078</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7394</LAST_LATITUDE>
    <REPORTDATE>2015/05/18 08:35:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BENOA JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>FADRIK KOSASIH TJUNG</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>FADRIK KOSASIH TJUNG</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4958947</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2081</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7392</LAST_LATITUDE>
    <REPORTDATE>2015/04/16 03:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BALI PERMAI 189</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJAI ALI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJAI ALI</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4960956</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,0492</LAST_LONGITUDE>
    <LAST_LATITUDE>0,9719</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER MUTIARA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KIM SENG</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KIM SENG</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957428</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,4183</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,4722</LAST_LATITUDE>
    <REPORTDATE>2015/05/21 10:21:00</REPORTDATE>
    <NAMA_KAPAL_VMS>EVIA PEARL</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TRI KUSUMA GRAHA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TRI KUSUMA GRAHA, PT.</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957429</NO_TRANSMITTER>
    <LAST_LONGITUDE>140,4183</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,4722</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 04:44:00</REPORTDATE>
    <NAMA_KAPAL_VMS>KHAMSIN - A</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TRI KUSUMA GRAHA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TRI KUSUMA GRAHA, PT.</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811035835</NO_TRANSMITTER>
    <LAST_LONGITUDE>99,806</LAST_LONGITUDE>
    <LAST_LATITUDE>2,994</LAST_LATITUDE>
    <REPORTDATE>2015/06/01 11:30:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ATLANTIC</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HASBUN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HASBUN</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>33518</NO_TRANSMITTER>
    <LAST_LONGITUDE>103,407</LAST_LONGITUDE>
    <LAST_LATITUDE>0,988</LAST_LATITUDE>
    <REPORTDATE>2013/05/27 05:52:53</REPORTDATE>
    <NAMA_KAPAL_VMS>DELI KARIMUN INDAH</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AWI Als TENG LIE OEI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AWI Als TENG LIE OEI</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4956252</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2061</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7378</LAST_LATITUDE>
    <REPORTDATE>2015/04/21 18:47:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 33</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957186</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2083</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7392</LAST_LATITUDE>
    <REPORTDATE>2015/01/23 23:57:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEKAR MANDIRI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HARYANI SUDARMO, IR</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HARYANI SUDARMO, IR</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4956293</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2075</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7428</LAST_LATITUDE>
    <REPORTDATE>2013/10/29 02:46:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SURYA TERBIT 889</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>GLOBAL PAHALA SAMUDERA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>GLOBAL PAHALA SAMUDERA, PT</NAMA_PERUSAHAAN>
    <ID_WPP> </ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957178</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2064</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7381</LAST_LATITUDE>
    <REPORTDATE>2015/04/12 22:26:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 222</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR BENOA BALI, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR BENOA BALI, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4956259</NO_TRANSMITTER>
    <LAST_LONGITUDE>139,7531</LAST_LONGITUDE>
    <LAST_LATITUDE>-9,3503</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 05:13:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 86</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718, 713</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811035798</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,681</LAST_LONGITUDE>
    <LAST_LATITUDE>3,781</LAST_LATITUDE>
    <REPORTDATE>2013/06/20 20:26:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ORIENT STAR</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>DUTARYO PUTRA SAMUDRA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>DUTARYO PUTRA SAMUDRA, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4956267</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,0492</LAST_LONGITUDE>
    <LAST_LATITUDE>0,9722</LAST_LATITUDE>
    <REPORTDATE>2015/06/03 00:20:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER MAS</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KING LIE</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KING LIE</NAMA_PERUSAHAAN>
    <ID_WPP>712, 711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811703170</NO_TRANSMITTER>
    <LAST_LONGITUDE>107,148</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,327</LAST_LATITUDE>
    <REPORTDATE>2015/05/29 01:56:00</REPORTDATE>
    <NAMA_KAPAL_VMS>NANDO JAYA - 02</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HARAPAN JAYA MAJU, CV.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HARAPAN JAYA MAJU, CV.</NAMA_PERUSAHAAN>
    <ID_WPP>572, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31076468</NO_TRANSMITTER>
    <LAST_LONGITUDE>111,155</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,70155</LAST_LATITUDE>
    <REPORTDATE>2015/04/10 04:12:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEKAR JAYA BAHARI - 05</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SUTINAH</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SUTINAH</NAMA_PERUSAHAAN>
    <ID_WPP>713, 712</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4517907</NO_TRANSMITTER>
    <LAST_LONGITUDE>109,6722</LAST_LONGITUDE>
    <LAST_LATITUDE>-4,2206</LAST_LATITUDE>
    <REPORTDATE>2015/05/12 02:48:00</REPORTDATE>
    <NAMA_KAPAL_VMS>KUSUMA KARYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>NORAWATI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>NORAWATI</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4952214</NO_TRANSMITTER>
    <LAST_LONGITUDE>102,4119</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,9119</LAST_LATITUDE>
    <REPORTDATE>2015/04/04 03:51:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LANGSUNG JAYA UTAMA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ANAVY</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ANAVY</NAMA_PERUSAHAAN>
    <ID_WPP>572, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4949265</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,1856</LAST_LONGITUDE>
    <LAST_LATITUDE>1,1161</LAST_LATITUDE>
    <REPORTDATE>2014/10/14 22:19:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT BARELANG 7</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JARINGAN BARELANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JARINGAN BARELANG, PT</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4949293</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,2644</LAST_LONGITUDE>
    <LAST_LATITUDE>1,2394</LAST_LATITUDE>
    <REPORTDATE>2014/10/14 23:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT BARELANG 9</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JARINGAN BARELANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JARINGAN BARELANG, PT</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4946309</NO_TRANSMITTER>
    <LAST_LONGITUDE>106,1822</LAST_LONGITUDE>
    <LAST_LATITUDE>5,1478</LAST_LATITUDE>
    <REPORTDATE>2013/06/20 19:43:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT NATUNA - 07</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RISWAN CITRA PRATAMA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RISWAN CITRA PRATAMA, PT.</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4946310</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,44</LAST_LONGITUDE>
    <LAST_LATITUDE>1,5597</LAST_LATITUDE>
    <REPORTDATE>2014/04/25 00:54:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT NATUNA - 06</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RISWAN CITRA PRATAMA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RISWAN CITRA PRATAMA, PT.</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4905085</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2056</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7433</LAST_LATITUDE>
    <REPORTDATE>2015/05/15 02:14:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LESTARI ABADI - 3</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>I KOMANG REDANA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>I KOMANG REDANA</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4892546</NO_TRANSMITTER>
    <LAST_LONGITUDE>67,8153</LAST_LONGITUDE>
    <LAST_LATITUDE>-36,6153</LAST_LATITUDE>
    <REPORTDATE>2013/04/22 09:19:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LINGSAR - 07</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AMIR</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AMIR</NAMA_PERUSAHAAN>
    <ID_WPP>573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4887557</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,1183</LAST_LONGITUDE>
    <LAST_LATITUDE>1,0042</LAST_LATITUDE>
    <REPORTDATE>2014/04/17 10:34:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT BARELANG 18</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JARINGAN BARELANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JARINGAN BARELANG, PT</NAMA_PERUSAHAAN>
    <ID_WPP> </ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4881753</NO_TRANSMITTER>
    <LAST_LONGITUDE>105,9708</LAST_LONGITUDE>
    <LAST_LATITUDE>4,8608</LAST_LATITUDE>
    <REPORTDATE>2014/10/05 09:19:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT BARELANG - 21</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JARINGAN BARELANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JARINGAN BARELANG, PT</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4881755</NO_TRANSMITTER>
    <LAST_LONGITUDE>104,1025</LAST_LONGITUDE>
    <LAST_LATITUDE>0,98</LAST_LATITUDE>
    <REPORTDATE>2014/06/05 11:18:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT BARELANG - 15</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JARINGAN BARELANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JARINGAN BARELANG, PT</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4864286</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2056</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7436</LAST_LATITUDE>
    <REPORTDATE>2015/02/18 01:55:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BERKAT MENTARI - 88</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>NYOMAN SARYA, BSC</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>NYOMAN SARYA, BSC</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870404</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7922</LAST_LONGITUDE>
    <LAST_LATITUDE>1,72</LAST_LATITUDE>
    <REPORTDATE>2014/09/15 08:25:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER BINTANG REZEKI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>FAREL RUMAHORBO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>FAREL RUMAHORBO</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870369</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7108</LAST_LONGITUDE>
    <LAST_LATITUDE>1,1033</LAST_LATITUDE>
    <REPORTDATE>2014/04/25 23:09:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LIMA DAI - 5</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TONNY AGUSTINUS LUMBANTOBING</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TONNY AGUSTINUS LUMBANTOBING</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870368</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7894</LAST_LONGITUDE>
    <LAST_LATITUDE>1,7292</LAST_LATITUDE>
    <REPORTDATE>2013/02/15 15:08:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUN TERI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>PANTAS M. LUMBAN TOBING</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>PANTAS M. LUMBAN TOBING</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811704921</NO_TRANSMITTER>
    <LAST_LONGITUDE>108,586</LAST_LONGITUDE>
    <LAST_LATITUDE>-1,443</LAST_LATITUDE>
    <REPORTDATE>2014/09/21 03:54:00</REPORTDATE>
    <NAMA_KAPAL_VMS>INDAH LESTARI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJITRO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJITRO</NAMA_PERUSAHAAN>
    <ID_WPP>711</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4867763</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2075</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7419</LAST_LATITUDE>
    <REPORTDATE>2015/05/04 04:57:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 70</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
    <ID_WPP>718</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870392</NO_TRANSMITTER>
    <LAST_LONGITUDE>98,7925</LAST_LONGITUDE>
    <LAST_LATITUDE>1,7272</LAST_LATITUDE>
    <REPORTDATE>2014/06/12 06:26:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ABADI MAKMUR</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HONG TJAI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HONG TJAI</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4870390</NO_TRANSMITTER>
    <LAST_LONGITUDE>96,6525</LAST_LONGITUDE>
    <LAST_LATITUDE>1,7525</LAST_LATITUDE>
    <REPORTDATE>2013/04/25 11:49:00</REPORTDATE>
    <NAMA_KAPAL_VMS>DAUN HIJAU</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJA LIE</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJA LIE</NAMA_PERUSAHAAN>
    <ID_WPP>572</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4867765</NO_TRANSMITTER>
    <LAST_LONGITUDE>115,2089</LAST_LONGITUDE>
    <LAST_LATITUDE>-8,7386</LAST_LATITUDE>
    <REPORTDATE>2015/06/02 05:05:00</REPORTDATE>
    <NAMA_KAPAL_VMS>HEN - 8</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BALI TUNA SEGAR, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BALI TUNA SEGAR, PT</NAMA_PERUSAHAAN>
    <ID_WPP>714, 573</ID_WPP>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4867754</NO_TRANSMITTER>
    <LAST_LONGITUDE>106,7989</LAST_LONGITUDE>
    <LAST_LATITUDE>-6,0944</LAST_LATITUDE>
    <REPORTDATE>2013/04/15 15:07:00</REPORTDATE>
    <NAMA_KAPAL_VMS>CROWN MARITIM JAYA - III</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KENT GUI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KENT GUI</NAMA_PERUSAHAAN>