<?xml version="1.0" ?>
<!DOCTYPE main [
  <!ELEMENT main (DATA_RECORD*)>
  <!ELEMENT DATA_RECORD (NO_TRANSMITTER?,LAST_LONGITUDE?,LAST_LATITUDE?,REPORTDATE?,NAMA_KAPAL_VMS?,PEMILIK_KAPAL?,NAMA_PERUSAHAAN?)+>
  <!ELEMENT NO_TRANSMITTER (#PCDATA)>
  <!ELEMENT LAST_LONGITUDE (#PCDATA)>
  <!ELEMENT LAST_LATITUDE (#PCDATA)>
  <!ELEMENT REPORTDATE (#PCDATA)>
  <!ELEMENT NAMA_KAPAL_VMS (#PCDATA)>
  <!ELEMENT PEMILIK_KAPAL (#PCDATA)>
  <!ELEMENT NAMA_PERUSAHAAN (#PCDATA)>
]>
<main>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811701026</NO_TRANSMITTER>
    <LAST_LONGITUDE>134.874</LAST_LONGITUDE>
    <LAST_LATITUDE>-4.442</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:43:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BAHAGIA BARU</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SA HIAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SA HIAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811707388</NO_TRANSMITTER>
    <LAST_LONGITUDE>124.898</LAST_LONGITUDE>
    <LAST_LATITUDE>-11.119</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:42:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEJAHTERA I</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JIAN TONG</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JIAN TONG</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408863</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.14646</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.86191</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:42:00</REPORTDATE>
    <NAMA_KAPAL_VMS>HASIL MELIMPAH - III A</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>LAW A GWAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>LAW A GWAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4822400</NO_TRANSMITTER>
    <LAST_LONGITUDE>101.8569</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.8583</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>HARAPAN JAYA PERKASA - II</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>NARDY</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>NARDY</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4735137</NO_TRANSMITTER>
    <LAST_LONGITUDE>89.2025</LAST_LONGITUDE>
    <LAST_LATITUDE>0.9717</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUN JAYA - IV</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>NG BOBBY FOLENTIEN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>NG BOBBY FOLENTIEN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4583763</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.9667</LAST_LONGITUDE>
    <LAST_LATITUDE>4.7442</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ANUGERAH LESTARI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TONDI MARYONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TONDI MARYONO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4612396</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.4028</LAST_LONGITUDE>
    <LAST_LATITUDE>3.3125</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SURYA CITRA NUSANTARA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>RAMITO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>RAMITO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4587962</NO_TRANSMITTER>
    <LAST_LONGITUDE>98.4219</LAST_LONGITUDE>
    <LAST_LATITUDE>-1.8239</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ONASSIS</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AMAN INDAYANG</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AMAN INDAYANG</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4915621</NO_TRANSMITTER>
    <LAST_LONGITUDE>108.3514</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.5</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>KHORINA BAHARI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ANTONI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ANTONI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4878126</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.8033</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.0994</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEKAR KENCANA - 03</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MEKAR KENCANA MAKMUR, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MEKAR KENCANA MAKMUR, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811701474</NO_TRANSMITTER>
    <LAST_LONGITUDE>135.835</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.887</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BALENO JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AI TJU</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AI TJU</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4958980</NO_TRANSMITTER>
    <LAST_LONGITUDE>115.2069</LAST_LONGITUDE>
    <LAST_LATITUDE>-8.7417</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SURYA TERANG - 88</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>GOLDEN TUNA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>GOLDEN TUNA, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4520463</NO_TRANSMITTER>
    <LAST_LONGITUDE>111.155</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.7019</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEMANGET</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>H. SODIKIN BIN SALMAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>H. SODIKIN BIN SALMAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4499038</NO_TRANSMITTER>
    <LAST_LONGITUDE>99.8967</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.6478</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>RUKUN ARTHA SANTOSO - 09</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4558594</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.2075</LAST_LONGITUDE>
    <LAST_LATITUDE>2.7678</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SURYA CITRA NUSANTARA - III</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ASAN MATJIK</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ASAN MATJIK</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4736926</NO_TRANSMITTER>
    <LAST_LONGITUDE>113.6506</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.695</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ARTHA MINA PERKASA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HARYONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HARYONO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4680851</NO_TRANSMITTER>
    <LAST_LONGITUDE>113.3806</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.7214</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>INKA MINA MAKMUR 381</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KUB. RUKUN SANTOSO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KUB. RUKUN SANTOSO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408239</NO_TRANSMITTER>
    <LAST_LONGITUDE>125.15687</LAST_LONGITUDE>
    <LAST_LATITUDE>6.07708</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEGAH CERIA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SURYA FISHERIES SEJAHTERA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SURYA FISHERIES SEJAHTERA, PT.</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4737603</NO_TRANSMITTER>
    <LAST_LONGITUDE>99.4069</LAST_LONGITUDE>
    <LAST_LATITUDE>-1.2419</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>TERATAI III</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KARYA AGUNG LESTARI JAYA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KARYA AGUNG LESTARI JAYA, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4541685</NO_TRANSMITTER>
    <LAST_LONGITUDE>140.3792</LAST_LONGITUDE>
    <LAST_LATITUDE>-9.6344</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:41:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER NELAYAN 108</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>DARVIN JIMMYTAT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>DARVIN JIMMYTAT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4630687</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.8981</LAST_LONGITUDE>
    <LAST_LATITUDE>1.2994</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>DIANA MULIA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>DAHLIANA KENANGA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>DAHLIANA KENANGA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40409587</NO_TRANSMITTER>
    <LAST_LONGITUDE>124.83995</LAST_LONGITUDE>
    <LAST_LATITUDE>1.5228</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MINA SAMUDERA - A</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HARIANTO DAVID</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HARIANTO DAVID</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4953774</NO_TRANSMITTER>
    <LAST_LONGITUDE>139.4803</LAST_LONGITUDE>
    <LAST_LATITUDE>-9.2353</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SANJAYA - 1688</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HENRY LAU</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HENRY LAU</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4583761</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.8292</LAST_LONGITUDE>
    <LAST_LATITUDE>3.3308</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ANUGERAH - 9</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TONGDY HASIM AL ONG TIONG SENG </PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TONGDY HASIM AL ONG TIONG SENG </NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4558583</NO_TRANSMITTER>
    <LAST_LONGITUDE>115.2061</LAST_LONGITUDE>
    <LAST_LATITUDE>-8.7508</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>PUTRA HARAPAN</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>WILLIAM SUTIOSO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>WILLIAM SUTIOSO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40409610</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.80297</LAST_LONGITUDE>
    <LAST_LATITUDE>2.13497</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>HARAPAN JAYA - XXXIII</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>AMAT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>AMAT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40409996</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.80206</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.09823</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>EDO SEHATI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SUBRYANTO SUHARTO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SUBRYANTO SUHARTO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957182</NO_TRANSMITTER>
    <LAST_LONGITUDE>140.1467</LAST_LONGITUDE>
    <LAST_LATITUDE>-9.5525</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 103</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4725813</NO_TRANSMITTER>
    <LAST_LONGITUDE>87.9483</LAST_LONGITUDE>
    <LAST_LATITUDE>2.1431</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>GARUDA JAYA V</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HERYANTO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HERYANTO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4548783</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.6178</LAST_LONGITUDE>
    <LAST_LATITUDE>3.1581</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>4548783</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4630686</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.6589</LAST_LONGITUDE>
    <LAST_LATITUDE>1.3194</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>JAYA UTAMA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JASMAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JASMAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40409793</NO_TRANSMITTER>
    <LAST_LONGITUDE>116.65127</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.77953</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG MAS UNION</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>NGAYADI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>NGAYADI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4823824</NO_TRANSMITTER>
    <LAST_LONGITUDE>97.0597</LAST_LONGITUDE>
    <LAST_LATITUDE>-8.1667</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MEKAR KENCANA - 05</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MEKAR KENCANA MAKMUR, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MEKAR KENCANA MAKMUR, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40510792</NO_TRANSMITTER>
    <LAST_LONGITUDE>116.58937</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.87824</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>RUKUN MINA SANTOSA - 06</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>EKO BUDIYONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>EKO BUDIYONO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4824491</NO_TRANSMITTER>
    <LAST_LONGITUDE>114.9883</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.4678</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG MAS TIMUR</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ASMANDI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ASMANDI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4634926</NO_TRANSMITTER>
    <LAST_LONGITUDE>116.5425</LAST_LONGITUDE>
    <LAST_LATITUDE>-4.2861</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MITRA ARINDO - I</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ANTON GUNARSO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ANTON GUNARSO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4830041</NO_TRANSMITTER>
    <LAST_LONGITUDE>125.2094</LAST_LONGITUDE>
    <LAST_LATITUDE>1.4503</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SABANG JAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJAI ALI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJAI ALI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4533202</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.0756</LAST_LONGITUDE>
    <LAST_LATITUDE>0.4358</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MAJU JAYA - 88</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811034702</NO_TRANSMITTER>
    <LAST_LONGITUDE>128.188</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.679</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>LAUT HALMAHERA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SINAR ABADI CEMERLANG, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SINAR ABADI CEMERLANG, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408422</NO_TRANSMITTER>
    <LAST_LONGITUDE>99.93753</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.62104</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:40:00</REPORTDATE>
    <NAMA_KAPAL_VMS>HASIL MELIMPAH - 8</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>LIM LE HWA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>LIM LE HWA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4644948</NO_TRANSMITTER>
    <LAST_LONGITUDE>96.4197</LAST_LONGITUDE>
    <LAST_LATITUDE>1.1039</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>VICTORY BARU</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HENDRA ANGRONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HENDRA ANGRONO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>86811035800</NO_TRANSMITTER>
    <LAST_LONGITUDE>99.356</LAST_LONGITUDE>
    <LAST_LATITUDE>3.486</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG BAHARI</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TEDY SURJONO NILAM</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TEDY SURJONO NILAM</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408685</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.06094</LAST_LONGITUDE>
    <LAST_LATITUDE>3.16021</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG SEJAHTERA 8</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>CHANDRA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>CHANDRA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4689403</NO_TRANSMITTER>
    <LAST_LONGITUDE>103.4983</LAST_LONGITUDE>
    <LAST_LATITUDE>0.8675</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUKSES PERKASA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MUSDI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MUSDI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4907108</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.7775</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.1053</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG SUKSES MAKMUR - 8</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>PONIMAN KESUMA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>PONIMAN KESUMA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4956364</NO_TRANSMITTER>
    <LAST_LONGITUDE>90.4006</LAST_LONGITUDE>
    <LAST_LATITUDE>-1.7869</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MERPATI - 2</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ARIEF SURYADI HALIM</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ARIEF SURYADI HALIM</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4717443</NO_TRANSMITTER>
    <LAST_LONGITUDE>108.0303</LAST_LONGITUDE>
    <LAST_LATITUDE>3.1678</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>PRIMA SUKSES - 2</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TJENDRA TJANDRA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TJENDRA TJANDRA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4557009</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.4267</LAST_LONGITUDE>
    <LAST_LATITUDE>-0.2067</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SRI INTAN - 2</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>JEFFRY SUPRIANTO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>JEFFRY SUPRIANTO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4795707</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.7994</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.0939</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SINAR JAYA PERKASA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SIDI YANA</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SIDI YANA</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4960956</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.4308</LAST_LONGITUDE>
    <LAST_LATITUDE>3.4075</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER MUTIARA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KIM SENG</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KIM SENG</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4922738</NO_TRANSMITTER>
    <LAST_LONGITUDE>109.3061</LAST_LONGITUDE>
    <LAST_LATITUDE>2.8372</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>JALA SUTRA III</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HOLDY CHUARDI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HOLDY CHUARDI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4628853</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.8256</LAST_LONGITUDE>
    <LAST_LATITUDE>3.4628</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MAJU JAYA - 688</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SUNO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SUNO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408502</NO_TRANSMITTER>
    <LAST_LONGITUDE>98.78955</LAST_LONGITUDE>
    <LAST_LATITUDE>1.72892</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>INDRAGIRI </NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>EFRAIM TJIA, SE</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>EFRAIM TJIA, SE</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4558590</NO_TRANSMITTER>
    <LAST_LONGITUDE>116.9403</LAST_LONGITUDE>
    <LAST_LATITUDE>-4.5553</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BAHTERA WIJAYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SUYONO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SUYONO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4953779</NO_TRANSMITTER>
    <LAST_LONGITUDE>129.0744</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.0019</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ENDE JAYA KARYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ARABIKATAMA KHATULISTIWA FISHING INDUSTRY, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ARABIKATAMA KHATULISTIWA FISHING INDUSTRY, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4565583</NO_TRANSMITTER>
    <LAST_LONGITUDE>105.3364</LAST_LONGITUDE>
    <LAST_LATITUDE>2.4092</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>AC. MILAN-MILAN - II</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HADIANTO SALIM,SH</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>HADIANTO SALIM,SH</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31085966</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.29973</LAST_LONGITUDE>
    <LAST_LATITUDE>2.92155</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>DEWATA SAMUDERA</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31085977</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.00141</LAST_LONGITUDE>
    <LAST_LATITUDE>4.332267</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>TRI JAYA 6</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31072276</NO_TRANSMITTER>
    <LAST_LONGITUDE>108.62188</LAST_LONGITUDE>
    <LAST_LATITUDE>3.26055</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MINA CEMERLANG</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4512142</NO_TRANSMITTER>
    <LAST_LONGITUDE>114.8331</LAST_LONGITUDE>
    <LAST_LATITUDE>-8.1886</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>4512142</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4694821</NO_TRANSMITTER>
    <LAST_LONGITUDE>100.2631</LAST_LONGITUDE>
    <LAST_LATITUDE>13.5322</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>NEW STREAM</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SAMUDERA PRATAMA JAYA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SAMUDERA PRATAMA JAYA, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408056</NO_TRANSMITTER>
    <LAST_LONGITUDE>109.2307</LAST_LONGITUDE>
    <LAST_LATITUDE>2.43723</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>CITRA UTAMA </NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>CING HAI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>CING HAI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408689</NO_TRANSMITTER>
    <LAST_LONGITUDE>114.00849</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.51035</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BERKAH RAHMAT</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KAMILIN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KAMILIN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40511958</NO_TRANSMITTER>
    <LAST_LONGITUDE>114.84977</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.04417</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>ATLANTIK-9</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31085980</NO_TRANSMITTER>
    <LAST_LONGITUDE>108.30863</LAST_LONGITUDE>
    <LAST_LATITUDE>-4.18075</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>MULYA HATI 02</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>31085974</NO_TRANSMITTER>
    <LAST_LONGITUDE>107.0073</LAST_LONGITUDE>
    <LAST_LATITUDE>2.728083</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINTANG LAUT - I</NAMA_KAPAL_VMS>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40409940</NO_TRANSMITTER>
    <LAST_LONGITUDE>114.94255</LAST_LONGITUDE>
    <LAST_LATITUDE>-5.38973</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>FAJAR  MULYA</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>SUMARSO, H</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>SUMARSO, H</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4960951</NO_TRANSMITTER>
    <LAST_LONGITUDE>99.9753</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.1689</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:39:00</REPORTDATE>
    <NAMA_KAPAL_VMS>PULAU CENDRAWASIH III</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>MARKUN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>MARKUN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>40408861</NO_TRANSMITTER>
    <LAST_LONGITUDE>106.8036</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.09834</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BERKAH MELIMPAH</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>LAW A GWAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>LAW A GWAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4957403</NO_TRANSMITTER>
    <LAST_LONGITUDE>103.1336</LAST_LONGITUDE>
    <LAST_LATITUDE>-36.3608</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - 17</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4949258</NO_TRANSMITTER>
    <LAST_LONGITUDE>139.8558</LAST_LONGITUDE>
    <LAST_LATITUDE>-9.4289</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>TWINDO 18</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>GLOBAL TWINDO PERKASA, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>GLOBAL TWINDO PERKASA, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4905103</NO_TRANSMITTER>
    <LAST_LONGITUDE>128.1831</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.6753</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEAVIC AREMAR</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ERA SISTEM INFORMASINDO, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ERA SISTEM INFORMASINDO, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4907100</NO_TRANSMITTER>
    <LAST_LONGITUDE>128.1794</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.6794</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEAVIC REEFER</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>ERA SISTEM INFORMASINDO, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>ERA SISTEM INFORMASINDO, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4624199</NO_TRANSMITTER>
    <LAST_LONGITUDE>102.5347</LAST_LONGITUDE>
    <LAST_LATITUDE>-34.7981</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BANDAR NELAYAN - II</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>BANDAR NELAYAN, PT</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>BANDAR NELAYAN, PT</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4619473</NO_TRANSMITTER>
    <LAST_LONGITUDE>109.9519</LAST_LONGITUDE>
    <LAST_LATITUDE>-3.6394</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SEMANGAT BARU</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TAGIMIN KAMAN</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TAGIMIN KAMAN</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4544916</NO_TRANSMITTER>
    <LAST_LONGITUDE>137.3361</LAST_LONGITUDE>
    <LAST_LATITUDE>-6.3506</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>BINAMA  No. 10</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>DWI BINA UTAMA, PT.</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>DWI BINA UTAMA, PT.</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4611036</NO_TRANSMITTER>
    <LAST_LONGITUDE>104.3917</LAST_LONGITUDE>
    <LAST_LATITUDE>-23.9192</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>KM.UNITED -29</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>TUHI</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>TUHI</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4587264</NO_TRANSMITTER>
    <LAST_LONGITUDE>108.205</LAST_LONGITUDE>
    <LAST_LATITUDE>1.9656</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SUMBER LAUT - IV</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>YANTO</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>YANTO</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4608711</NO_TRANSMITTER>
    <LAST_LONGITUDE>125.5694</LAST_LONGITUDE>
    <LAST_LATITUDE>3.0903</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>INKA MINA 720</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>KUB. TUDE JAYA ANUGERAH &#40; RONALD BUDIMAN&#41;</PEMILIK_KAPAL>
    <NAMA_PERUSAHAAN>KUB. TUDE JAYA ANUGERAH &#40; RONALD BUDIMAN&#41;</NAMA_PERUSAHAAN>
  </DATA_RECORD>
  <DATA_RECORD>
    <NO_TRANSMITTER>4556773</NO_TRANSMITTER>
    <LAST_LONGITUDE>115.2072</LAST_LONGITUDE>
    <LAST_LATITUDE>-8.7408</LAST_LATITUDE>
    <REPORTDATE>2015/05/22 21:38:00</REPORTDATE>
    <NAMA_KAPAL_VMS>SINAR MAS - 88</NAMA_KAPAL_VMS>
    <PEMILIK_KAPAL>HASONO</PEMILIK_KAPAL>